version = 0.1
[default.deploy.parameters]
stack_name = "ocsf"
resolve_s3 = true
s3_prefix = "ocsf"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"ocsfazurelogs\""
image_repositories = []
